from __future__ import annotations

from pathlib import Path
from typing import Any

from jinja2 import Environment, PackageLoader, select_autoescape

TEMPLATE_STR = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ results.title }} - Test Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; font-size: 14px; color: #1a1a1a; background: #f5f5f5; padding: 20px; }
  .container { max-width: 1200px; margin: 0 auto; }
  .header { background: #1a56db; color: white; padding: 24px 32px; border-radius: 8px 8px 0 0; }
  .header h1 { font-size: 24px; margin-bottom: 4px; }
  .header .meta { opacity: 0.85; font-size: 13px; }
  .summary { background: white; padding: 20px 32px; border-bottom: 1px solid #e5e7eb; display: flex; gap: 24px; }
  .summary-item { text-align: center; }
  .summary-item .value { font-size: 28px; font-weight: 700; }
  .summary-item .label { font-size: 12px; color: #6b7280; text-transform: uppercase; }
  .value.passed { color: #059669; }
  .value.failed { color: #dc2626; }
  .value.skipped { color: #6b7280; }
  .group { background: white; margin-top: 16px; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .group-header { padding: 16px 24px; font-weight: 600; font-size: 16px; border-bottom: 1px solid #e5e7eb; display: flex; justify-content: space-between; align-items: center; }
  .group-header .status-badge { font-size: 12px; padding: 2px 10px; border-radius: 999px; font-weight: 600; }
  .status-badge.passed { background: #d1fae5; color: #065f46; }
  .status-badge.failed { background: #fee2e2; color: #991b1b; }
  .step { padding: 12px 24px; border-bottom: 1px solid #f3f4f6; }
  .step:last-child { border-bottom: none; }
  .step-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; }
  .step-name { font-weight: 500; }
  .meas-table { width: 100%; border-collapse: collapse; font-size: 13px; }
  .meas-table th { text-align: left; padding: 6px 8px; background: #f9fafb; border-bottom: 1px solid #e5e7eb; font-weight: 500; color: #6b7280; font-size: 11px; text-transform: uppercase; }
  .meas-table td { padding: 6px 8px; border-bottom: 1px solid #f3f4f6; }
  .verdict { font-weight: 600; }
  .verdict.passed { color: #059669; }
  .verdict.failed { color: #dc2626; }
  .footer { text-align: center; padding: 24px; color: #9ca3af; font-size: 12px; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>{{ results.title }}</h1>
    <div class="meta">{{ results.timestamp }} &middot; v{{ results.version }}</div>
  </div>

  {% set all_steps = [] %}
  {% for gname, group in results.groups.items() %}
    {% for step in group.steps %}
      {% set _ = all_steps.append(step) %}
    {% endfor %}
  {% endfor %}
  {% set passed = all_steps | selectattr("status", "equalto", "passed") | list | length %}
  {% set failed = all_steps | selectattr("status", "equalto", "failed") | list | length %}
  <div class="summary">
    <div class="summary-item"><div class="value passed">{{ passed }}</div><div class="label">Passed</div></div>
    <div class="summary-item"><div class="value failed">{{ failed }}</div><div class="label">Failed</div></div>
    <div class="summary-item"><div class="value">{{ all_steps | length }}</div><div class="label">Total</div></div>
  </div>

  {% for gname, group in results.groups.items() %}
  <div class="group">
    <div class="group-header">
      <span>{{ group.name }}</span>
      <span class="status-badge {{ group.status }}">{{ group.status }}</span>
    </div>
    {% for step in group.steps %}
    <div class="step">
      <div class="step-header">
        <span class="step-name">{{ step.name }}</span>
        <span class="verdict {{ step.status }}">{{ step.status }}</span>
      </div>
      {% if step.error %}
      <div style="color:#dc2626;font-size:13px;margin-bottom:8px;">{{ step.error }}</div>
      {% endif %}
      {% if step.measurements %}
      <table class="meas-table">
        <thead><tr><th>Measurement</th><th>Value</th><th>Limit</th><th>Verdict</th></tr></thead>
        <tbody>
        {% for m in step.measurements %}
        <tr>
          <td>{{ m.name }}</td>
          <td>{{ m.value }}</td>
          <td>{% if m.limits %}{{ m.limits[0].op }} {{ m.limits[0].value }}{% endif %}</td>
          <td class="verdict {{ m.verdict }}">{{ m.verdict }}</td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
      {% endif %}
    </div>
    {% endfor %}
  </div>
  {% endfor %}

  <div class="footer">
    Generated by valicore v{{ version }} &mdash; {{ results.timestamp }}
  </div>
</div>
</body>
</html>"""


class HTMLReporter:
    def __init__(self, template_str: str | None = None):
        self._env = Environment(autoescape=select_autoescape(["html"]))
        self._template = self._env.from_string(template_str or TEMPLATE_STR)

    def render(self, results: dict[str, Any], version: str = "0.1.0") -> str:
        return self._template.render(results=results, version=version)

    def write(self, results: dict[str, Any], path: str | Path, version: str = "0.1.0") -> Path:
        path = Path(path)
        html = self.render(results, version=version)
        path.write_text(html, encoding="utf-8")
        return path
